on:
  - pull_request
jobs:
  install_formula:
    runs-on: macos-15-intel
    steps:
      -
        name: Checkout
        uses: actions/checkout@v6
      -
        name: Install rainforest-cli
        run: |
          brew tap --custom-remote rainforestapp/public $GITHUB_WORKSPACE
          brew info rainforestapp/public/rainforest-cli
          brew install rainforestapp/public/rainforest-cli
      -
        name: Check rainforest works
        env:
          URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REF: ${{ github.event.pull_request.head.ref }}
        run: |
          VERSION=`rainforest --version --skip-update`
          echo $VERSION
          curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data "{ \"body\": \"This update reported its version as \`$VERSION\` and we're on branch \`$REF\` 🤞\" }"
